services:
  - type: web
    name: summarizer-backend
    env: python
    plan: free
    region: oregon
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "uvicorn backend.main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: GROQ_API_KEY
        sync: false  # You'll set this manually in Render dashboard
    autoDeploy: true
